name: snakebyte
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flame: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  all_lint_rules_community: ^0.0.15
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
